INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (1, 'Vidros e travas elétricas', 'Vidros e travas elétricas');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (2, 'Ar-Condicionado', 'Ar-Condicionado');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (3, 'Direção hidráulica', 'Direção hidráulica');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (4, 'Airbags frontais', 'Airbags frontais');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (5, 'Airbags laterais', 'Airbags laterais');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (6, 'Sistema modernizado de som', 'Sistema modernizado de som');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (7, 'Cruise Control', 'Piloto automático');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (8, 'Sensor de proximidade', 'Sensor de proximidade');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (9, 'Calha de chuva', 'Calha de chuva');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (10, 'Controle de tração', 'Controle de tração');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (11, 'Pintura anti-corrosão', 'Pintura anti-corrosão');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (12, 'GPS', 'Sistema de posicionamento global');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (13, 'Função Economic/Sport', 'Função Economic/Sport');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (14, 'Sistema multimídia', 'Sistema multimídia');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (15, 'Bluetooth', 'Bluetooth');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (16, 'Câmera traseira', 'Câmera traseira');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (17, 'Estepe', 'Estepe');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (18, 'Freio ABS', 'Freio ABS');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (19, 'Vidros com fechamento em um toque', 'Vidros com fechamento em um toque');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (20, 'Partida remota', 'Partida remota');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (21, 'Aquecimento nos bancos', 'Aquecimento nos bancos');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (22, 'Controle de estabilidade', 'Controle de estabilidade');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (23, 'Roda de liga leve', 'Roda de liga leve');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (24, 'Câmbio automático', 'Câmbio automático');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (25, 'Banco de couro', 'Banco de couro');
INSERT INTO ITEM (ID_ITEM, NOME, DESCRICAO) VALUES (26, 'Farol de neblina', 'Farol de neblina');