CREATE TABLE CHASSI(
    ID_CHASSI INTEGER PRIMARY KEY,
    DATA_REGISTRO TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE BOLETIM_SERVICO(
    ID_BOLETIM VARCHAR(50) PRIMARY KEY,
    DESCRICAO VARCHAR(100),
    DATA_REGISTRO TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE ITEM(
    ID_ITEM INTEGER PRIMARY KEY,
    NOME VARCHAR(100),
    DESCRICAO VARCHAR(100),
    DATA_REGISTRO TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE LOGICA(
    ID_LOGICA INTEGER PRIMARY KEY,
    ID_ITEM INTEGER,
    CONDICAO VARCHAR(100),
    DATA_REGISTRO TIMESTAMP DEFAULT SYSDATE,
    FOREIGN KEY (ID_ITEM) REFERENCES ITEM (ID_ITEM)
);

CREATE TABLE CHASSI_BOLETIM(
    ID_CHASSI INTEGER,
    ID_BOLETIM VARCHAR(50),
    STATUS VARCHAR(50),
    DATA_REGISTRO TIMESTAMP DEFAULT SYSDATE,
    PRIMARY KEY (ID_CHASSI, ID_BOLETIM),
    FOREIGN KEY (ID_CHASSI) REFERENCES CHASSI (ID_CHASSI),
    FOREIGN KEY (ID_BOLETIM) REFERENCES BOLETIM_SERVICO (ID_BOLETIM)
);

CREATE TABLE CHASSI_ITEM(
    ID_CHASSI INTEGER,
    ID_ITEM INTEGER,
    DATA_INSTALACAO TIMESTAMP DEFAULT SYSDATE,
    PRIMARY KEY (ID_CHASSI, ID_ITEM),
    FOREIGN KEY (ID_CHASSI) REFERENCES CHASSI (ID_CHASSI),
    FOREIGN KEY (ID_ITEM) REFERENCES ITEM (ID_ITEM)
);

CREATE TABLE BOLETIM_ITEM(
    ID_BOLETIM VARCHAR(50),
    ID_ITEM INTEGER,
    DATA_REGISTRO TIMESTAMP DEFAULT SYSDATE,
    PRIMARY KEY (ID_BOLETIM, ID_ITEM),
    FOREIGN KEY (ID_BOLETIM) REFERENCES BOLETIM_SERVICO(ID_BOLETIM),
    FOREIGN KEY (ID_ITEM) REFERENCES ITEM (ID_ITEM)
);

CREATE TABLE MUDANCAS (
    ID_MUDANCA INTEGER PRIMARY KEY,
    DATA_REGISTRO TIMESTAMP DEFAULT SYSDATE,
    TABELA_MODIFICADA VARCHAR(100),
    ID_REGISTRO_MODIFICADO INTEGER,
    CAMPO_MODIFICADO VARCHAR(100),
    VALOR_ANTERIOR VARCHAR(100),
    VALOR_NOVO VARCHAR(100),
    ID_USUARIO INTEGER
);